### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-docs#6]
Currently there are still broken links in the documentation.

**Comment by girijakar** [comment]
Hi, I would like to work on this issue.

**Comment by rht** [comment]
@girijakar sounds good. You can automate finding the dead links with https://www.deadlinkchecker.com/, where you feed in 1 page, e.g. https://github.com/inblockio/aqua-docs/blob/main/content/en/docs/protocol/whitepaper.md. Make sure to choose the single webpage option.

Make sure to use Markdown relative link for internal link, such as https://github.com/inblockio/aqua-docs/blob/80a134c808cca2c92d14d90b2cdd0d8cb93910fd/content/en/docs/protocol/whitepaper.md?plain=1#L22.

**Comment by FantasticoFox** [comment]
@girijakar do you need any help? We are happy if you send a PR.

**Comment by girijakar** [comment]
Hieee @FantasticoFox, I had previously sent PRs about the broken links and at that time those were also merged. I couldn't find any more broken links.

**Comment by rht** [comment]
Yeah, this has been fixed. The PRs that closed this issue: #7, #8, #9, #10, #11.
